name:                codewars
version:             0.1.0.0
github:              "githubuser/codewars"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/codewars#readme>

dependencies:
- base >= 4.7 && < 5
- containers

default-extensions:
- OverloadedStrings
- DeriveGeneric
- DeriveAnyClass

library:
  source-dirs: src
  when:
  - condition: false
    other-modules: Paths_codewars

executables:
  codewars-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - codewars
    when:
    - condition: false
      other-modules: Paths_codewars

tests:
  codewars-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - codewars
    when:
    - condition: false
      other-modules: Paths_codewars
